# Generated by Django 3.1.2 on 2020-10-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201004_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
